### ISSUE TITLE
NLB instance Security groups are ignored 

### ISSUE THREAD

**Issue by Deshke** [kubernetes/cloud-provider-aws#109]
**What happened**:
maybe more a documentation issue. 

The annotation for `service.beta.kubernetes.io/aws-load-balancer-security-groups` is being ignored and security rules are being created in the "main" node security group that is responsible for nodes. 

**What you expected to happen**:

the specified security group is used 

**How to reproduce it (as minimally and precisely as possible)**:

1) create a new security group
2) add the security group to instances
3) spawn a new service 

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-xxxxxxx
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
```
4) check the primary node security group of the cluster for a new rule description `kubernetes.io/rule/nlb/client=xxxxxx` 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.6
- Cloud provider or hardware configuration: aws/kops 

/kind bug
