### ISSUE TITLE
Kubernetes  1.11.x => 1.12.x AWS Cloud Provider fails to align AWSInstances <=> Kubernetes Instances

### ISSUE THREAD

**Issue by danielsand** [kubernetes/cloud-provider-aws#14]
Hello,

i have chef + terraform + kubeadm glued together to raise quickly a Kubernetes cluster in any version inside of AWS with nginx ingress + ELB installed via default.

Starting of Kubernetes Version 1.11.x => this stops working.

The AWS Cloud provider doesn't populate the ELB with the EC2 Nodes anymore.

The Only hint i have is that this Log lines appears in the Kubernetes-Controller pod.

```
node ".....compute.internal" did not have ProviderID set
node ".....compute.internal" did not have ProviderID set
node ".....compute.internal" did not have ProviderID set
```

has some tagging changed or needs to be adapted ?

Reference:
https://github.com/kubernetes/kubeadm/issues/973

**Comment by danielsand** [comment]
side note:

node.Spec.ProviderID

is not set on the cluster nodes under 1.11.x

**Comment by varuns-zetaris** [comment]
Is there any solution to this issue. We are also facing the same problem when running k8s in AWS

**Comment by ArchiFleKs** [comment]
I had the same issue, are you using v1alpha3 ?

Here is my InitConfig :

```
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  kubeletExtraArgs:
    cloud-provider: "aws"
```

It turns out that it is not use by the node, you need a JoinConfiguration:

```
apiVersion: kubeadm.k8s.io/v1alpha3
discoveryTokenAPIServers:
- 127.0.0.1:6443
discoveryTokenUnsafeSkipCAVerification: true
kind: JoinConfiguration
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  kubeletExtraArgs:
    cloud-provider: "aws"
``` 

Mine was missing the AWS cloud provider therefore node were not using it and were not getting providerID.
