### ISSUE TITLE
AWS NLB not spanning across AZs after a cluster update

### ISSUE THREAD

**Issue by subhankarc** [kubernetes/cloud-provider-aws#206]
**What happened**:

I am facing a strange problem with the loadbalancer type service on AWS. Following are the steps I am doing.

1. I created a cluster(based on Gardener) with one node in 1 AZ, eu-central-1a.
2. 1. I created a loadbalancer type service. I used  `service.beta.kubernetes.io/aws-load-balancer-type: nlb` annotation to let it create an AWS NLB behind.
3. I have 1 pod behind the service, and my pod gets the request correctly.
4. Now I add another node in the clusrer in a different AZ, eu-central-1b
5. I increase number of pods to 2, and my pods are now sitting in two different nodes. The nodes are from two different AZs
6. The second pod never gets the request. So I checked the AWS NLB config, and there I see that the NLB is still assigned with 1 availability zone and corresponding subnet of eu-central-1a  and in the target group, even though two nodes are there in the target list, the second node is marked as unused with error as “Target is in an Availability Zone that is not enabled for the load balancer”
7. If I create a new service now, the corresponding NLB is properly assigned with the required AZs and target status are proper.

**What you expected to happen**:

My question here is that shouldn’t Kubernetes automatically assign the new AZ(subnet) when a cluster is scaled up to have multiple AZ or is there a setting I am missing here maybe ?

I tried the same steps with adding `service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'` annotation and that didn't help either. I also tried changing the port of the service to let it reconcile, but that didn't help.

**How to reproduce it (as minimally and precisely as possible)**:

The above steps can be followed to reproduce it.

The service details look like below.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
  labels:
    app: service1
  name: service1
spec:
  externalTrafficPolicy: Local
  ports:
  - name: https
    nodePort: 32479
    port: 443
    protocol: TCP
    targetPort: 10449
  selector:
    name: service1
  sessionAffinity: None
  type: LoadBalancer
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.5
- Cloud provider or hardware configuration: AWS

/kind bug
