### ISSUE TITLE
Classic ELB with IPv6

### ISSUE THREAD

**Issue by Kent1** [kubernetes/cloud-provider-aws#224]
I created a loadbalancer service type. The generated SG is something like 

![image](https://user-images.githubusercontent.com/83018/119771971-c69a5980-bebe-11eb-8919-b5ca38ebb444.png)

corresponding to the service 

```
apiVersion: v1
kind: Service
metadata:
  name: whois
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ports:
    - port: 43
...
```

I would like to add IPv6 support to it. Adding ::/0 to loadBalancerSourceRanges however gives the following error in the controller:

```
E0527 05:28:15.366915       1 controller.go:244] error processing service blabla (will retry): failed to ensure load balancer: error authorizing security group ingress: "InvalidParameterValue: CIDR block ::/0 is malformed\n\tstatus code: 400, request id: c07966b8-5b58-4d51-bd9f-033554f675ef"
```

Is that maybe not supported yet ?
I use EKS 1.18
