### ISSUE TITLE
Creation of a NLB ignores proxy protocol annotation

### ISSUE THREAD

**Issue by L30Bola** [kubernetes/cloud-provider-aws#234]
**What happened**:
When NLB is created, it's listeners' target groups are created but they aren't enabling Proxy Protocol

**What you expected to happen**:
When the NLB is created, after the creation and attachment of the target groups, they should enable proxy protocol.

**How to reproduce it (as minimally and precisely as possible)**:
Create a service with the specific annotation:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  name: test-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
```

**Anything else we need to know?**:

At first, I thought that #180 would have fixed, as I tested on `1.16.15`, `1.17.11` and `1.18.18` clusters (on them the `aws-load-balancer-cross-zone-load-balancing-enabled` annotation was also ignored. #180 fixed that on `1.20.*`), but the target groups created weren't with Proxy Protocol enabled. Maybe it's important to note that on NLBs, only Proxy Protocol v2 is available.

**Environment**:
- Kubernetes version (use `kubectl version`):  Tried on `1.16.15`, `1.17.11`, `1.18.18` and `1.20.7`
- Cloud provider or hardware configuration: The cluster is using `c5.2xlarge` on all 6 nodes.
- OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1018-aws
- Install tools: Kops with Terraform
- Others: 

/kind bug
