### ISSUE TITLE
EBS storage class not working, GetCloudProvider return nil

### ISSUE THREAD

**Issue by MoShiKB** [kubernetes/cloud-provider-aws#239]
Hey, 
I'm trying to use out-of-tree with RKE cluster.

**What happened**:
the cloud manager deployment finished successfully, node controller and service controller works perfectly.
afterward, I created a new EBS storage class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "false"
```
Then I created a new pod with PVC using the storage class.
but it seems the PVC cannot create any new EBS on the cloud, and return the following error:
`Failed to provision volume with StorageClass "gp2": Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead`

**What you expected to happen**:
A new EBS will create on AWS, and the pod will start running using it.

**How to reproduce it (as minimally and precisely as possible)**:
1. created a new cluster using Rancher with the external provider.
2. deployed aws-controller-manager-0.0.2 chart which initialized the cluster provider. - The same happened with the manifest deployment.
3. created a new storage class using the code above.
4. created new deployment and PVC and attach them.
5. a new EBS should be created on the cloud.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration: **aws cloud provider**
- OS (e.g. from /etc/os-release): **5.4.0-1045-aws 18.04.1-Ubuntu**
- Tools: deployed using rancher 2.5.8

/kind bug
