### ISSUE TITLE
EKS 1.21 Service type=LoadBalancer does not support ServiceAppProtocol

### ISSUE THREAD

**Issue by EvgeniGordeev** [kubernetes/cloud-provider-aws#270]
`ServiceAppProtocol` is supposed to be `stable` in [1.20+](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol). 

**Scenario**: 

Applying

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-lb
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:<redacted>:certificate/<redacted>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      targetPort: 80
      appProtocol: https
    - name: 5671-tcp
      port: 5671
      targetPort: 5671-tcp
      appProtocol: tcp
```

creates a Classic LB with the following listeners:
![image](https://user-images.githubusercontent.com/3843966/132758263-57a8d5bd-e75b-49ae-b312-e5c6b1216d7b.png)

If `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http` is uncommented:
![image](https://user-images.githubusercontent.com/3843966/132758006-3982e72a-f8af-4f94-b8db-bea55f38712b.png)

**Expected**:

`appProtocol` takes care of LB Listener protocol, something like: 
![image](https://user-images.githubusercontent.com/3843966/132758534-2427d29d-2c6d-4872-93b3-727e944e779e.png)

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug
