### ISSUE TITLE
classic load balancer is not forwarding client-ip address

### ISSUE THREAD

**Issue by iambumblehead** [kubernetes/cloud-provider-aws#338]
Hello, I want a Service that sends client ip addresses to the connected pod.

According to [the document here,][0] Classic Load Balancer Service should add the client ip address in the "x-forwarded-for" header, however, the application running in the pod logs "x-forwarded-for" headers with internal ip-addresses such as 192.168.82.211 and 192.168.21.59.
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-for

The Service resource is defined with `type: LoadBalancer` and `externalTrafficPolicy: Local` per k8s documentation for "preserving-the-client-source-ip" https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

```yaml
---
kind: Service
apiVersion: v1
metadata:
  name: xxxx
  namespace: xxxx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: server
      port: 443
      targetPort: 8000
```

I've tried various configurations of "Classic Load Balancer" and "Network Load Balancer" to try and preserve client ip address. Whatever I try, the application logs show internal ips from "x-forwarded-for" headers.

The Ingress uses annotation "nginx.ingress.kubernetes.io/backend-protocol: HTTPS", in case that is important

Thank you for any reply or suggestion

[0]: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-for

/triage support
