### ISSUE TITLE
Problem to access to pod's logs on a k3s cluster deployment

### ISSUE THREAD

**Issue by gelopfalcon** [kubernetes/cloud-provider-aws#401]
**What happened**:
It issue only happens when installing the aws-cloud-controller-manager.

When the command `kubectl logs <pod_name>` is executed it throws an error:
```
Error from server: Get "https://ip-172-31-46-216.us-east-2.compute.internal:10250/containerLogs/kube-system/aws-cloud-controller-manager-hcx9z/aws-cloud-controller-manager": x509: certificate is valid for ip-172-31-46-216, localhost, not ip-172-31-46-216.us-east-2.compute.internal
```

It seems that the certificate isn't considerating to the local-hostname but when the k3s cluster is created, it is receiving the local-hostname:

```
--tls-san $(curl -s http://169.254.169.254/latest/meta-data/local-hostname) 
```

In addition, the serving-kube-apiserver.crt file is using the local-hostname (ip-172-31-46-216.us-east-2.compute.internal) in their DNS values:

```
openssl x509 -noout -ext subjectAltName -in serving-kube-apiserver.crt 
X509v3 Subject Alternative Name: 
    DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:rancher-demo-internal-a82678715f0b9299.elb.us-east-2.amazonaws.com, DNS:rancher-demo-external-39526e587d8f9fc4.elb.us-east-2.amazonaws.com,  DNS:ip-172-31-46-216.us-east-2.compute.internal, DNS:localhost, DNS:ip-172-31-46-216, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:172.31.46.216, IP Address:10.235.0.1
```

I created a new  helm chart based on your chart version v1.22.0 and passed the certificates that k3s cluster created above (created and mounted a volume):

```
     containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
          - name: k3s-keys
            mountPath: /mnt/tls
          args:
            {{- range .Values.args }}
            - {{ . }}
            {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: k3s-keys
        hostPath:
          path: /var/lib/rancher/k3s/server/tls
          type: Directory
```

And passing the values in the chart:

```
      - --tls-cert-file=/mnt/tls/serving-kube-apiserver.crt
      - --tls-private-key-file=/mnt/tls/serving-kube-apiserver.key
```

but the problem continues. 

Again, it only happens when aws-cloud-controller-manager is installed in the k3s cluster.

It is the chart that we used and found the problem:

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: aws-cloud-controller-manager
  namespace: kube-system
spec:
  chart: https://github.com/kubernetes/cloud-provider-aws/releases/download/helm-chart-aws-cloud-controller-manager-0.0.6/aws-cloud-controller-manager-0.0.6.tgz
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    args:
      - --v=2
      - --cloud-provider=aws
      - --cluster-cidr=10.1.0.0/16
      - - --tls-cert-file=/mnt/tls/serving-kube-apiserver.crt
      - --tls-private-key-file=/mnt/tls/serving-kube-apiserver.key
    image:
      tag: v1.22.0
    hostNetworking: true
    nodeSelector:
      node-role.kubernetes.io/master: "true"  

```
BTW, I used a lot of your versions but the problem is the same.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

- Install a k3s cluster
- Pass the following parameters
```
 --disable servicelb \
      --tls-san $(curl -s http://169.254.169.254/latest/meta-data/local-hostname) \
      --cluster-init \
      --disable local-storage \
      --disable traefik \
      --flannel-backend=none --disable-network-policy \
      --kubelet-arg="cloud-provider=external" \
      --kubelet-arg="provider-id=aws:///$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)/$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.22.8+k3s1
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu 18.04.6 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): x86_64 x86_64 x86_64 GNU/Linux

/kind bug

**Comment by olemarkus** [comment]
the CCM doesn't have a role in returning logs. So the error you are seeing are coming from either an incorrectly configured apiserver or an incorrectly configured kubelet. Most likely it is the kubelet certificate that does not contain the correct name.

**Comment by gelopfalcon** [comment]
If you read my ticket, I'm explaining that the problem was found after installing cloud provider aws. 
- My cluster was logging without problems.
- Installed cloud provider aws.
- The logs problems started.

I think that your answer isn't considerating my explanation.

Install k3s cluster
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION='v${install_k3s_version}' %{ if is_k3s_server } %{ if k3s_datastore_endpoint != "sqlite" }K3S_DATASTORE_ENDPOINT='${k3s_datastore_endpoint}'%{ endif } %{ endif }  sh -s server --disable-cloud-controller \
      --token ${k3s_cluster_secret} \
      --disable servicelb \
      ${k3s_tls_san} \
      --tls-san $(curl -s http://169.254.169.254/latest/meta-data/local-hostname) \
      --cluster-init \
      --disable local-storage \
      --disable traefik \
      --flannel-backend=none --disable-network-policy \
      --kubelet-arg="cloud-provider=external" \
      --kubelet-arg="provider-id=aws:///$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)/$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
```

Install cloud provider aws

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: aws-cloud-controller-manager
  namespace: kube-system
spec:
  chart: https://github.com/kubernetes/cloud-provider-aws/releases/download/helm-chart-aws-cloud-controller-manager-0.0.6/aws-cloud-controller-manager-0.0.6.tgz
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    args:
      - --v=2
      - --cloud-provider=aws
      - --cluster-cidr=10.1.0.0/16
    image:
      tag: v1.22.0
    hostNetworking: true
    nodeSelector:
      node-role.kubernetes.io/master: "true" 
```
