### ISSUE TITLE
Helm chart does not select control-plane nodes on 1.24

### ISSUE THREAD

**Issue by kwohlfahrt** [kubernetes/cloud-provider-aws#430]
**What happened**:

When deploying the cloud provider from the Helm Chart using the configuration below, the daemonset selects no nodes to deploy on.

```
USER-SUPPLIED VALUES:
args:
- --cloud-provider=aws
- --cluster-cidr=10.0.0.0/12
- --cluster-name=kai-test-cluster
- --configure-cloud-routes=false
image:
  tag: v1.24.1
```

This additional configuration is required (note that `node-role.kubernetes.io/master: null` is required to _remove_ this selector):

```
nodeSelector:
  node-role.kubernetes.io/control-plane: ""
  node-role.kubernetes.io/master: null
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/control-plane
- effect: NoSchedule
  key: node-role.kubernetes.io/master
```

**What you expected to happen**:

I expect the helm chart to successfully deploy without having to specify custom labels and taints.

**How to reproduce it (as minimally and precisely as possible)**:

Provision a kubernetes version 1.24 cluster, for example with `kubeadm`. Add the above configuration snippets to `values.yaml`, and install the provider with `helm install --repo 'https://kubernetes.github.io/cloud-provider-aws' --values aws-values.yaml --version 0.0.6 aws-cloud-controller-manager aws-cloud-controller-manager`.

**Anything else we need to know?**:

The `control-plane` node labels and taints have been present [since v1.20](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#urgent-upgrade-notes), and the `master` label and taint will be removed in v1.25 (for reference, see the [v1.24 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes)), the next upstream release. It seems like now is a good time to make this transition.

I'm happy to open a PR for this.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24.2
- Cloud provider or hardware configuration: AWS EC2 (not EKS)
- OS (e.g. from /etc/os-release): Ubuntu 20.04.4
- Kernel (e.g. `uname -a`): `5.13.0-1031-aws`
- Install tools: `kubeadm`
- Others:

/kind bug
