### ISSUE TITLE
Support on-premises nodes connected to the AWS control plane by permitting non-AWS instances to join, making auth configmap less clunky

### ISSUE THREAD

**Issue by doctorpangloss** [kubernetes/cloud-provider-aws#441]
https://github.com/kubernetes/cloud-provider-aws/blob/3f8bdc5713cba89b01e2441a67596c1444013b5e/pkg/providers/v2/instances.go#L138

I use a VPC Gateway to connect on-premises Linux and Windows nodes to the EKS control plane. Right now, they just pretend to be some random instance in order to work around the control plane check referenced above.

Can you also check for an annotation, imagine `provider=on-premises` and permit admission if such an annotation exists?

Setting up the `auth` configmap is pretty clunky too. I created a 0 instance nodegroup with eksctl and hijacked its rolearn to give each physical node:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  # todo: investigate merging the aws auth map. not sure if we actually need these
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
data:
  mapRoles: |
    - rolearn: arn:aws:iam::###########:role/eksctl-XXXXXXX
      username: system:node:exact-node-hostname
      groups:
        - system:bootstrappers
        - system:nodes
        # for windows nodes
        - eks:kube-proxy-windows
```

Maybe this can also be addressed too?
