### ISSUE TITLE
Override load-balancer healthcheck target via annotations

### ISSUE THREAD

**Issue by bordeuax** [kubernetes/cloud-provider-aws#49]
**What would you like to be added**:  
Have a kubernetes service annotation like "service.beta.kubernetes.io/aws-load-balancer-healthcheck-target", that can override the default healthcheck target and follow the format from aws-sdk for Go lang , for more info see  Target field  https://docs.aws.amazon.com/sdk-for-go/api/service/elb/#HealthCheck.
   

**Why is this needed**:
I have two uses cases 
1.  One of our component require client certificate authentication and all the traffic is handled by LB as TCP ,  HealthCheck from LB doing simple TCP connections  that generate a lot of logs with SSL errors in ours pods. To avoid this it's will be nice to deploy the K8S service with : 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    project: 
  annotations:
       service.beta.kubernetes.io/aws-load-balancer-healthcheck-target:  "SSL:3356"
```
if the port is not specifyed then by default is from application 
```
apiVersion: v1
kind: Service
metadata:
  labels:
    project: 
  annotations:
       service.beta.kubernetes.io/aws-load-balancer-healthcheck-target:  "SSL"
```

2.  The healthcheck of application is accessible via different port(comparing with applicaiton port) and have a specific path, in this case the solution can be : 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    project: 
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-healthcheck-target:  "HTTP:3636/app/status/lb"

```

/kind feature
/remove-lifecycle stale

**Comment by vvbogdanov87** [comment]
Kuberntes 1.14 [uses SSL health checks for ELBs when backend protocol is SSL/HTTPS](https://github.com/kubernetes/kubernetes/pull/70309)
But for the health check pIng target k8s selects first port in the listeners list
https://github.com/2rs2ts/kubernetes/blob/72895a84a9670d6f6f8921681c5bbe4b2745319e/pkg/cloudprovider/providers/aws/aws.go#L3602
Without annotation described above, you MUST set https/SSL port to be first in the `spec.ports`
I had a service spec:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
```
After I upgraded to k8s 1.14 I got `OutOfService` for all instances in AWS LB. I had to change the spec to
```
  ports:
    - name: https
      protocol: TCP
      port: 443
    - name: http
      protocol: TCP
      port: 80
```
