### ISSUE TITLE
`service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout` is never applied

### ISSUE THREAD

**Issue by esierra-stratio** [kubernetes/cloud-provider-aws#822]
**What happened**:
`service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout` is never applied.

**What you expected to happen**:
Annotation must set the healthcheck timeout to 15s instead of 10s (default value).
![image](https://github.com/kubernetes/cloud-provider-aws/assets/102975650/37f15df9-ccfa-415b-bf96-3998925bcd88)

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "15"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "15"
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): EKS 1.26
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from /etc/os-release): 
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```
- Kernel (e.g. `uname -a`):
`Linux ip-10-0-219-103.eu-west-1.compute.internal 5.10.201-191.748.amzn2.x86_64 #1 SMP Mon Nov 27 18:28:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

/kind bug
