### ISSUE TITLE
NLB does not map to manual EndpointSlice

### ISSUE THREAD

**Issue by Ghilteras** [kubernetes/cloud-provider-aws#859]
I have a Service without a selector which creates a public NLB. Then I have an `EndpointSlice` that maps to a FQDN like this:

```yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-service
  namespace: default
  labels:
    kubernetes.io/service-name: my-service
addressType: FQDN
ports:
  - name: tcp
    protocol: TCP
    port: 8080
endpoints:
  - addresses:
      - "myfoo-service.com"
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
    - name: tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
```

**What happened**:
I cannot reach the FQDN using the Public Load Balancer DNS name

**What you expected to happen**:
I should be able to reach the FQDN using the Load Balancer DNS name

**How to reproduce it (as minimally and precisely as possible)**:
I apply the manifest above and I connect to the public DNS of the load balancer.

**Anything else we need to know?**:
I can reach out the external service if I use a Service type `ExternalName` but I cannot map this Service to a LB Service b/c Services can only map to pod labels or custom Endpoints and the EndpointSlice does not work for some reason

**Environment**:
- Kubernetes version 1.21.9

/kind bug
