### ISSUE TITLE
NLB services with "externalTrafficPolicy: Local" route traffic to nodes that cannot handle it for a short time when a node joins the cluster

### ISSUE THREAD

**Issue by LHCGreg** [kubernetes/cloud-provider-aws#87]
**What happened**: In our EKS cluster we have an nginx ingress as an NLB service with externalTrafficPolicy set to Local. It uses an NLB instead of ELB/ALB because it is part of an API Gateway VPC Link, which can only use an NLB.

We are seeing the following behavior: When a new node (even one that does not/cannot run nginx) joins the kubernetes cluster, sometimes (maybe only when the new node is in the same AZ as nginx?), there will be a period of about 30 seconds when hitting our app via the API gateway returns a 500 error with a body of `{"message": "Internal server error"}`. This error does not show up in our app logs or the nginx logs. That body seems to be generated by API Gateway. Checking flow logs I was able to see what is happening.

Every node in the kubernetes cluster, even nodes that do not have an nginx pod, is a target in the NLB's target group. Only nodes that are running an nginx pod are considered healthy by the NLB. All other nodes in the target group are marked as unhealthy. When a new node not running nginx joins the cluster and the 500 errors happen, flow logs confirmed that traffic between the NLB and the new node on the NLB's health check port flows in both directions. After a while, traffic on the "real traffic" port occurs from the NLB to the new node, but not from the new node to the NLB.

If I SSH onto a non-nginx node in the cluster and run `curl http://<non-nginx node IP>:<health check port>`, I get a response from nginx. The non-nginx node routes the health check traffic to the nginx node. If I run `curl http://<non-nginx node IP>:<main traffic port>`, I do not get any response. The non-nginx node does not route "primary" traffic to the nginx node.

This means that when a new non-nginx node comes up, it passes the "active" health check that the NLB does by doing an HTTP request to /healthz on the health check port, because the node routes the request to an nginx node that is able to respond. But after it passes the initial health checks and enters the healthy state, the NLB is never able to connect to the new node on the "primary" traffic port, causing it to fail the NLB's "passive" health checks and the node enters the unhealthy state after failing to serve traffic for a bit.

**What you expected to happen**: I expected only nodes that actually run a pod belonging to the nginx service to be in the NLB's target group. Failing that, I would expect nodes to not forward health check traffic to the service when externalTrafficPolicy is Local. I could not see any way to configure those behaviors, please let me know if I am mistaken.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-gateway
  labels:
    app.kubernetes.io/name: ingress-nginx-gateway
    app.kubernetes.io/part-of: ingress-nginx-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nginx-ingress-clusterrole
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: nginx-ingress-role
  namespace: ingress-nginx-gateway
  labels:
    app.kubernetes.io/name: ingress-nginx-gateway
    app.kubernetes.io/part-of: ingress-nginx-gateway
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      # Defaults to "<election-id>-<ingress-class>"
      # Here: "<ingress-controller-leader>-<nginx>"
      # This has to be adapted if you change either parameter
      # when launching the nginx-ingress-controller.
      - "ingress-controller-leader-nginx-gateway"
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-gateway-clusterrole-nisa-binding
  labels:
    app.kubernetes.io/name: ingress-nginx-gateway
    app.kubernetes.io/part-of: ingress-nginx-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-ingress-clusterrole
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-serviceaccount
    namespace: ingress-nginx-gateway
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nginx-ingress-role-nisa-binding
  namespace: ingress-nginx-gateway
  labels:
    app.kubernetes.io/name: ingress-nginx-gateway
    app.kubernetes.io/part-of: ingress-nginx-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress-role
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-serviceaccount
    namespace: ingress-nginx-gateway
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx-gateway
  labels:
    app.kubernetes.io/name: ingress-nginx-gateway
    app.kubernetes.io/part-of: ingress-nginx-gateway
data:
  use-proxy-protocol: "false"
  use-forwarded-headers: "true"
  proxy-real-ip-cidr: "0.0.0.0/0"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: ingress-nginx-gateway
  labels:
    app.kubernetes.io/name: ingress-nginx-gateway
    app.kubernetes.io/part-of: ingress-nginx-gateway
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: ingress-nginx-gateway
  labels:
    app.kubernetes.io/name: ingress-nginx-gateway
    app.kubernetes.io/part-of: ingress-nginx-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
  namespace: ingress-nginx-gateway
  labels:
    app.kubernetes.io/name: ingress-nginx-gateway
    app.kubernetes.io/part-of: ingress-nginx-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-gateway
  labels:
    app.kubernetes.io/name: ingress-nginx-gateway
    app.kubernetes.io/part-of: ingress-nginx-gateway
  annotations:
    flux.weave.works/automated: 'true'
    fluxcd.io/tag.nginx-ingress-controller: semver:~0.26
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx-gateway
      app.kubernetes.io/part-of: ingress-nginx-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx-gateway
        app.kubernetes.io/part-of: ingress-nginx-gateway
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      nodeSelector:
        group: misc
      containers:
      - name: nginx-ingress-controller
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.2
        resources:
          requests:
            cpu: 250m
            memory: 2Gi
          limits:
            memory: 2Gi
        args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/nginx-configuration
        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
        - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
        - --publish-service=$(POD_NAMESPACE)/ingress-nginx
        - --annotations-prefix=nginx.ingress.kubernetes.io
        - --ingress-class=nginx-gateway
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
            # www-data -> 33
          runAsUser: 33
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: metrics
          containerPort: 10254
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx-gateway
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx-gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Application=nginx-ingress
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ingress-nginx-gateway
    app.kubernetes.io/part-of: ingress-nginx-gateway
  ports:
  - name: http
    port: 80
    targetPort: http
  type: LoadBalancer
```

**Anything else we need to know?**: I believe we can prevent the errors by setting externalTrafficPolicy to Cluster instead of Local. We were hoping to avoid the latency of an extra hop but will use Cluster if we have to.

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from /etc/os-release): Amazon Linux 2
- Kernel (e.g. `uname -a`): 4.14.154-128.181.amzn2.x86_64

/kind bug

**Comment by LHCGreg** [comment]
Also, switching the service to `externalTrafficPolicy: Cluster` did not remove the HTTP health check on the NLB. Health check failed on all nodes after the switch. I had to delete and recreate the service to get the NLB recreated to fix it.

**Comment by TBBle** [comment]
Per [Source IP for Services with Type=LoadBalancer](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-loadbalancer), the HTTP health check used for `externalTrafficPolicy: Local` (on `healthCheckNodePort`) should not be being routed to other nodes (this is not AWS-specific, but is part of kube-proxy), but perhaps the health-check is mis-setup and is seeing the 'failure' response (503) as successful. I don't see any changes [between 1.15 and 1.14](https://github.com/kubernetes/kubernetes/commits/ef6cba0b3635fc99eb658ecd4a29cf63bb234cb6/pkg/proxy/healthcheck/).

I am on 1.15, and was also seeing that it added all nodes to the NLB, rather than the nodes that hosted endpoints. I'm not sure why that is, but it seems a bad behaviour, particularly when (in my case) many of the nodes have taints that will exclude the Pods in the Service from ever living there.

However, I wasn't seeing (or perhaps only not noticing) the problem of newly-added nodes being temporarily healthy in the NLB's Target Group, so didn't replicate the '500' issue you're seeing. Perhaps it was fixed between 1.14 and 1.15, although I don't see any relevant changes in the [legacy-cloud-providers/aws history](https://github.com/kubernetes/kubernetes/commits/release-1.15/staging/src/k8s.io/legacy-cloud-providers/aws).

Is it possible you're seeing the same issue as https://github.com/kubernetes/kubernetes/issues/73362? That was fixed in Kubernetes 1.18, although it relates to failures in running pods, rather than pod startup.

**Comment by f-ld** [comment]
I have a similar issue.
In short:
- a pool of "nodes" (default ones, where most services will run) where nginx is running
- a pool of "myservice-nodes" where I have my service that is up/downscaling a lot (from 10 to 150 instances every day).

After being in touch with AWS support, I got confirmation that every time a new node is added, before healthcheck can test it and mark it unhealthy, it is considered as healthy by the NLB.

So in my case, the NLB will send TCP SYN requests to that new node where nginx port will never be opened and the consequence in our case is not a 500 but a connection timeout.

If the target group could be created with instance from a single instance group (in my case the pool of "default" nodes), then I would not have issues with instances created frequently in pool of "myservice-nodes" (which is like I said very frequent during the day) and it would only happen when a new "default" node is added (once a week maybe). So not fixed, but less visible.
Then I could also create a specific pool of nodes where I run my nginx instances, one that does not scale -> fixed, it would not happen any more.

**Comment by TBBle** [comment]
We just replicated the problem where switching from `externalTrafficPolicy: Local` to `externalTrafficPolicy: Cluster` leaves the Targetgroups in a bad state, on EKS.

```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

The Service is actually reporting the failure:
```
  Normal   ExternalTrafficPolicy   11m                  service-controller  Local -> Cluster
  Warning  SyncLoadBalancerFailed  11m                  service-controller  Error syncing load balancer: failed to ensure load balancer: Error modifying target group health check: "InvalidConfigurationRequest: You cannot change the health check protocol for a target group with the TCP protocol\n\tstatus code: 400, request id: 41fbdb6d-7b92-4a47-9386-1aef3f4242e2"
```

So the bug is that we can't change a health check protocol for a target group, and must delete and recreate them.

To fix it, I had to delete the NLB and the Target Groups, and then either wait for the LB creation to retry automatically, or trivially modify the Service so it immediately recreates the NLB.

I also note that in this mode, there's only three nodes in my target groups, I assume it's submitting one node in each AZ.

I would guess that the list of nodes to submit to the Load Balancer is a k8s choice, not an AWS Cloud Provider choice, as the AWS Cloud Provider doesn't check `externalTrafficPolicy` until it is setting up health checks, and the list of instances was already provided elsewhere.

**Comment by colinhoglund** [comment]
> After being in touch with AWS support, I got confirmation that every time a new node is added, before healthcheck can test it and mark it unhealthy, it is considered as healthy by the NLB.

I also noticed intermittent connection timeouts and verified traffic being sent to unready nodes with VPC flow logs. I got this same response from AWS support and they unfortunately were not able to provide any clear workarounds. :/

**Comment by TBBle** [comment]
Due to this limitation in NLB Instance mode, the best available workaround is probably to migrate to [NLB IP mode](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/service/nlb_ip_mode/), which requires the AWS LoadBalancer Controller, and Kubernetes 1.20 [or 1.18 if you're using EKS](https://github.com/aws/containers-roadmap/issues/981#issuecomment-715571153).

**Comment by avielb** [comment]
I can confirm having the exact same issue as well. 
@TBBle, did the upgrade and transition eks 1.18 with `nlb-ip` mode, fixed the issue for you?

**Comment by TBBle** [comment]
I haven't deployed it yet myself.

It _should_ fix the issue, because instead of AWS knowing about all your nodes and sending them traffic until they fail the first healthcheck because there's no Pod on that node, the NLB-IP mode is sending traffic to the Pod's IP, which is only added to the Service once that pod is actually ready to receive traffic.

**Comment by dberuben** [comment]
I have eks 1.18 i try to use the NLB-IP with no luck. 
Stuck with `  Normal  EnsuringLoadBalancer  119s  service-controller  Ensuring load balancer`

**Comment by TBBle** [comment]
@dberuben Have you installed the [AWS LoadBalancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/)? As far as I know, it's not deployed by default on EKS.

Not having the AWS LoadBalancer Controller installed is the only way I'd expect to see the "Ensuring load balancer" event, but no following failure event showing what went wrong.

If you have install the AWS LoadBalancer Controller, you'll have to check its logs to see what's gone wrong, see for example https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/933#issuecomment-488562937 on how to see the logs.

**Comment by dberuben** [comment]
@TBBle No i didn’t , let me try

**Comment by TBBle** [comment]
Okay. If you're still having trouble with the AWS LoadBalancer Controller after you install it (or having problems installing it), it probably makes more sense to open an issue on https://github.com/kubernetes-sigs/aws-load-balancer-controller than to ask questions on this ticket, as that way people who are currently working on and using it will be able to help.

**Comment by dberuben** [comment]
So was able to install AWS LoadBalancer Controller without any issue, i'm seeing my new `nlb-ip`, look like this when you describe the svc `k8s-nginxing...`.
I'm also seeing Pods IP in the TargetGroup.
The draining pods takes time but i think now i need to tweak my controller.

![image](https://user-images.githubusercontent.com/12519394/105365275-5e7cf380-5bfe-11eb-9089-6cce2c16cbd7.png)

**Comment by avielb** [comment]
same as me, I was able to install it and configure, can confirm now that the issue is not happening when working with `nlb-ip` configured

**Comment by TBBle** [comment]
Another method to improve this situation: [k8s 1.19](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.19) supports a new annotation [`service.beta.kubernetes.io/aws-load-balancer-target-node-labels`](https://kubernetes.io/docs/concepts/services-networking/service/#other-elb-annotations) which can limit the the instances used by a CLB or NLB by label. See https://github.com/kubernetes/kubernetes/pull/90943

It doesn't resolve this issue completely, but if your cluster is set up such that some nodes may _never_ have instances of the pod you're exposing with the load balancer, then you can at least avoid traffic ever being routed to them; your LB will still optimistically route traffic to nodes which _might_ have the pod, until they fail the health check.

I think `nlb-ip` is a better option for `externalTrafficPolicy: Local` (or even without that setting), and does not suffer this issue.

**Comment by kolorful** [comment]
> Per Source IP for Services with Type=LoadBalancer, the HTTP health check used for externalTrafficPolicy: Local (on healthCheckNodePort) should not be being routed to other nodes (this is not AWS-specific, but is part of kube-proxy)

@TBBle Somehow this seems not to be the case. I've tested in two clusters (v1.18 and v1.20) and requests to traffic port (30467, 30607) hangs on nodes that don't have Nginx Pod, but requests to healthCheckNodePort (30308) will be re-routed to the correct nodes somehow.

```
Service:
  externalTrafficPolicy: Local
  healthCheckNodePort: 30308
  ports:
  - name: http
    nodePort: 30467
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30607
    port: 443
    protocol: TCP
    targetPort: https
```

Update:
If I ssh into a worker node with no Nginx running, then curl the traffic port (127.0.0.1:30467) it works as well.
```
netstat -tulpn
tcp        0      0 0.0.0.0:30607           0.0.0.0:*               LISTEN      5582/kube-proxy
tcp        0      0 0.0.0.0:30320           0.0.0.0:*               LISTEN      5582/kube-proxy
tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN      5582/kube-proxy
tcp        0      0 0.0.0.0:31443           0.0.0.0:*               LISTEN      5582/kube-proxy
tcp        0      0 0.0.0.0:31860           0.0.0.0:*               LISTEN      5582/kube-proxy
tcp        0      0 0.0.0.0:30548           0.0.0.0:*               LISTEN      5582/kube-proxy
tcp        0      0 0.0.0.0:30070           0.0.0.0:*               LISTEN      5582/kube-proxy
tcp        0      0 0.0.0.0:31070           0.0.0.0:*               LISTEN      5582/kube-proxy
tcp        0      0 0.0.0.0:30467           0.0.0.0:*               LISTEN      5582/kube-proxy
tcp        0      0 0.0.0.0:32163           0.0.0.0:*               LISTEN      5582/kube-proxy
tcp        0      0 0.0.0.0:32681           0.0.0.0:*               LISTEN      5582/kube-proxy
tcp6       0      0 :::30308                :::*                    LISTEN      5582/kube-proxy
tcp6       0      0 :::10249                :::*                    LISTEN      5582/kube-proxy
```
