### ISSUE TITLE
Support Region for DescribeInstance Call

### ISSUE THREAD

**Issue by atsai1220** [kubernetes/cloud-provider-aws#939]
**What would you like to be added**:
- I would like to see the cloud-controller's DescribeInstance query also use the instance's region.

**Why is this needed**:
- This allows us to create workers in another region (not considering storage needs).

**Questions**:
- Are the repercussions for disabling node-life-cycle controller?

**Findings**:
Currently nodes from another region are "not found" by `node-life-cycle` controller and will be promptly deleted from the cluster after joining.

On 1.30.1 logs
```
node_controller.go:240] error syncing 'ip-10-117-161-37.ap-southeast-2.compute.internal': failed to get instance metadata for node ip-10-117-161-37.ap-southeast-2.compute.internal: instance not found, requeuing
node_controller.go:425] Initializing node ip-10-117-161-37.ap-southeast-2.compute.internal with cloud provider
node_controller.go:229] error syncing 'ip-10-117-161-37.ap-southeast-2.compute.internal': failed to get instance metadata for node ip-10-117-161-37.ap-southeast-2.compute.internal: instance not found, requeuing
```

Configuration
```
      containers:
        - args:
            - '--v=2'
            - '--cloud-provider=aws'
            - '--configure-cloud-routes=false'
          image: registry.k8s.io/provider-aws/cloud-controller-manager:v1.30.1
```

/kind feature
