### ISSUE TITLE
POD want real client ip

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes/cloud-provider-aws#99]
/triage support

hi all

In our business scenario, POD expects to obtain the real client IP address.

what can i do ?

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: xxx
  namespace: xxxxx
spec:
  clusterIP: 192.168.93.139
  externalTrafficPolicy: Cluster
  ports:
  - name: gate
    nodePort: 32410
    port: 20011
    protocol: TCP
    targetPort: 20011
  selector:
    serviceType: client-gate
  sessionAffinity: None
  type: LoadBalancer
```
